spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/apidb
#      username: wangab
#      password: wab123
server:
  context-path: /apiservice
  display-name: APIServerApplacation
  port: 8081
#logging:
#  level:
#    root: debug